#!/usr/bin/env python3
"""Generate the exhaustive publication index and the README reading-path blocks.

Source of truth (see docs/adr/0009):

- ``articles/*.md`` frontmatter decides Zenn-article membership (``published: true``),
  title, topics, slug (filename) and ``published_at`` (required when published).
- ``articles-en/<slug>.md`` (or legacy ``<slug>-en.md``) supplies the EN title.
- ``scripts/schedule.json`` only enriches with the recorded Dev.to URL.
- ``scripts/corpus.yml`` owns what has no frontmatter to parse: idea essays
  (note / Substack), deposited papers, and the research lines.
- ``scripts/reading_paths.yml`` owns the curated README routes (slug order + labels).

Outputs:

- ``docs/PUBLICATIONS.md`` — the single exhaustive index (articles, essays, papers).
- ``README.md`` / ``README.ja.md`` — only the block between the
  ``<!-- reading-paths:start -->`` / ``<!-- reading-paths:end -->`` markers.

Usage::

    python generate_article_index.py           # write outputs
    python generate_article_index.py --check   # exit 1 if any output is stale

Deterministic: no clock, no git — the same tree always renders the same text,
so ``--check`` is safe in CI. Future ``published_at`` values simply sort first.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

import frontmatter
import yaml

ZENN_BASE = "https://zenn.dev/shimo4228/articles"
START = "<!-- reading-paths:start -->"
END = "<!-- reading-paths:end -->"
GENERATED_NOTE = (
    "<!-- Generated by scripts/generate_article_index.py — do not edit by hand. "
    "Run `npm run generate:index`. -->"
)


@dataclass
class Article:
    slug: str
    title_ja: str
    topics: list[str]
    published_at: str  # "YYYY-MM-DD HH:MM" (JST) — as written in frontmatter
    title_en: str | None = None
    en_file: str | None = None  # repo-relative, e.g. "articles-en/foo.md"
    devto: str | None = None

    @property
    def zenn_url(self) -> str:
        return f"{ZENN_BASE}/{self.slug}"

    @property
    def date(self) -> str:
        return self.published_at[:10]


@dataclass
class Corpus:
    essays: list[dict]
    papers: list[dict]
    research_lines: list[dict]


@dataclass
class Route:
    id: str
    label: dict[str, str]
    reason: dict[str, str]
    slugs: list[str]
    title_en: dict[str, str] = field(default_factory=dict)  # fallback EN titles


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------


def _norm_date(value: object, slug: str) -> str:
    """Accept str / date / datetime (YAML may parse the field) → 'YYYY-MM-DD HH:MM'."""
    if value is None or value == "":
        raise ValueError(f"{slug}: published article without published_at")
    s = str(value).strip()
    m = re.match(r"^(\d{4}-\d{2}-\d{2})(?:[ T](\d{2}:\d{2}))?", s)
    if not m:
        raise ValueError(f"{slug}: unparseable published_at {s!r}")
    return f"{m.group(1)} {m.group(2) or '00:00'}"


def _en_slug(path: str) -> str:
    """'articles-en/foo-en.md' / 'articles-en/foo.md' → 'foo'."""
    stem = Path(path).stem
    return stem[:-3] if stem.endswith("-en") else stem


def load_articles(root: Path) -> list[Article]:
    schedule = json.loads((root / "scripts" / "schedule.json").read_text())
    # Keyed by slug, not filename: schedule.json may still name a renamed EN file
    # (e.g. "foo.md" recorded, "foo-en.md" on disk), and the URL must survive that.
    devto_by_slug: dict[str, str] = {}
    for a in schedule.get("articles", []):
        f = a.get("file", "")
        if f.startswith("articles-en/") and a.get("devto"):
            devto_by_slug[_en_slug(f)] = a["devto"]
    out: list[Article] = []
    for path in sorted((root / "articles").glob("*.md")):
        post = frontmatter.load(str(path))
        if post.get("published") is not True:
            continue
        slug = path.stem
        art = Article(
            slug=slug,
            title_ja=str(post.get("title", "")).strip(),
            topics=[str(t) for t in list(post.get("topics") or [])],
            published_at=_norm_date(post.get("published_at"), slug),
        )
        for cand in (f"articles-en/{slug}.md", f"articles-en/{slug}-en.md"):
            en_path = root / cand
            if en_path.exists():
                art.en_file = cand
                art.title_en = str(frontmatter.load(str(en_path)).get("title", "")).strip() or None
                art.devto = devto_by_slug.get(slug)
                break
        out.append(art)
    # newest first; slug as a stable tie-breaker
    out.sort(key=lambda a: (a.published_at, a.slug), reverse=True)
    return out


def load_corpus(root: Path, slugs: set[str]) -> Corpus:
    """corpus.yml — validated against the tree: referenced files and article slugs must exist."""
    data = yaml.safe_load((root / "scripts" / "corpus.yml").read_text()) or {}
    essays = list(data.get("essays", []))
    for e in essays:
        for lang in ("ja", "en"):
            ed = e.get(lang)
            if ed and ed.get("file") and not (root / ed["file"]).exists():
                raise ValueError(f"corpus.yml: essay {e.get('slug')!r} {lang} file missing: {ed['file']}")
        if not (e.get("ja") or e.get("en")):
            raise ValueError(f"corpus.yml: essay {e.get('slug')!r} has neither ja nor en")
    papers = list(data.get("papers", []))
    for pp in papers:
        for slug in pp.get("from", []) or []:
            if slug not in slugs:
                raise ValueError(f"corpus.yml: paper {pp.get('title')!r} references unknown slug {slug!r}")
    essays.sort(key=lambda e: (str(e["date"]), e["slug"]), reverse=True)
    papers.sort(key=lambda pp: (str(pp["date"]), pp["title"]), reverse=True)
    return Corpus(essays=essays, papers=papers, research_lines=list(data.get("research_lines", [])))


def load_routes(root: Path) -> list[Route]:
    data = yaml.safe_load((root / "scripts" / "reading_paths.yml").read_text()) or {}
    routes: list[Route] = []
    for r in data.get("routes", []):
        routes.append(
            Route(
                id=r["id"],
                label=dict(r["label"]),
                reason=dict(r.get("reason", {})),
                slugs=list(r["articles"]),
                title_en=dict(r.get("title_en", {})),
            )
        )
    return routes


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def _en_cell(a: Article) -> str:
    title = a.title_en or "EN"
    if a.devto:
        return f"[{title}]({a.devto})"
    if a.en_file:
        return f"[{title}](../{a.en_file}) (source)"
    return "—"


def _essay_cell(e: dict, lang: str, platform: str) -> str:
    ed = e.get(lang)
    if not ed:
        return "—"
    return f"[{ed['title']}]({ed['url']}) ({platform})"


def render_index(articles: list[Article], corpus: Corpus) -> str:
    paper_by_slug: dict[str, str] = {}
    for pp in corpus.papers:
        for slug in pp.get("from", []) or []:
            paper_by_slug[slug] = pp["title"]

    lines = [
        GENERATED_NOTE,
        "# Publications",
        "",
        "Everything published from this repository, newest first: "
        f"[{len(articles)} articles](#articles-zenn--devto) (Zenn JP / Dev.to EN), "
        f"[{len(corpus.essays)} idea essays](#idea-essays-note--substack) (note JP / Substack EN), "
        f"and [{len(corpus.papers)} papers](#papers) deposited from the "
        f"[research lines](#research-lines). "
        "Curated entry points are in the [README](../README.md).",
        "",
        "## Articles (Zenn / Dev.to)",
        "",
        "Japanese originals on Zenn; English editions on Dev.to, or as source in "
        "`articles-en/` when not cross-posted. Entries dated in the future are "
        "scheduled on Zenn.",
    ]
    month = None
    for a in articles:
        m = a.date[:7]
        if m != month:
            month = m
            lines += ["", f"### {month}", ""]
        topics = " ".join(f"`{t}`" for t in a.topics)
        lines.append(f"- **{a.date}** [{a.title_ja}]({a.zenn_url})")
        tail = f"  EN: {_en_cell(a)}" + (f" · {topics}" if topics else "")
        if a.slug in paper_by_slug:
            tail += f" · grew into the paper *{paper_by_slug[a.slug]}*"
        lines.append(tail)

    lines += [
        "",
        "## Idea essays (note / Substack)",
        "",
        "Japanese canonical on note, English edition on Substack; sources in `note/` and `substack/`.",
        "",
    ]
    for e in corpus.essays:
        lines.append(f"- **{e['date']}** JA: {_essay_cell(e, 'ja', 'note')}")
        lines.append(f"  EN: {_essay_cell(e, 'en', 'Substack')}")

    lines += [
        "",
        "## Papers",
        "",
        "Zenodo concept DOIs are canonical; SSRN entries are mirrors.",
        "",
    ]
    for pp in corpus.papers:
        lines.append(f"- **{pp['date']}** *{pp['title']}* — {pp['line']}")
        refs = [f"[Zenodo](https://doi.org/{pp['zenodo']})"]
        if pp.get("ssrn"):
            refs.append(f"[SSRN](https://doi.org/{pp['ssrn']})")
        grew = ", ".join(f"[{s}]({ZENN_BASE}/{s})" for s in (pp.get("from") or []))
        lines.append("  " + " · ".join(refs) + (f" · grew from: {grew}" if grew else ""))

    lines += [
        "",
        "## Research lines",
        "",
        "The five sibling research lines this corpus is the essay surface of "
        "(hub: <https://github.com/shimo4228/shimo4228>).",
        "",
    ]
    for rl in corpus.research_lines:
        lines.append(f"- [{rl['name']}]({rl['repo']}) — [DOI {rl['doi']}](https://doi.org/{rl['doi']})")
    lines.append("")
    return "\n".join(lines)


def render_routes(routes: list[Route], articles: list[Article], lang: str) -> str:
    by_slug = {a.slug: a for a in articles}
    lines = [START]
    for r in routes:
        lines += ["", f"### {r.label[lang]}", ""]
        if r.reason.get(lang):
            lines += [r.reason[lang], ""]
        for slug in r.slugs:
            a = by_slug.get(slug)
            if a is None:
                raise ValueError(f"reading_paths.yml: unknown or unpublished slug {slug!r}")
            if lang == "ja":
                lines.append(f"- [{a.title_ja}]({a.zenn_url})")
            elif a.devto:
                lines.append(f"- [{a.title_en or a.title_ja}]({a.devto})")
            elif a.en_file:  # translated but not cross-posted → the EN source in this repo
                lines.append(f"- [{a.title_en or a.title_ja}]({a.en_file}) (English source in this repo — not yet on Dev.to)")
            else:
                title = r.title_en.get(slug) or a.title_ja
                lines.append(f"- [{title}]({a.zenn_url}) (JP)")
    lines += ["", END]
    return "\n".join(lines)


def splice(text: str, block: str) -> str:
    """Replace the marker block inside README text; markers must exist exactly once."""
    s, e = text.count(START), text.count(END)
    if s != 1 or e != 1:
        raise ValueError(f"expected exactly one {START}/{END} pair, found {s}/{e}")
    head, rest = text.split(START, 1)
    _, tail = rest.split(END, 1)
    return head + block + tail


# ---------------------------------------------------------------------------
# Drive
# ---------------------------------------------------------------------------


def build_outputs(root: Path) -> dict[Path, str]:
    articles = load_articles(root)
    corpus = load_corpus(root, {a.slug for a in articles})
    routes = load_routes(root)
    outputs = {root / "docs" / "PUBLICATIONS.md": render_index(articles, corpus)}
    for name, lang in (("README.md", "en"), ("README.ja.md", "ja")):
        p = root / name
        outputs[p] = splice(p.read_text(), render_routes(routes, articles, lang))
    return outputs


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=(__doc__ or "").split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="fail if outputs are stale")
    ap.add_argument("--root", type=Path, default=Path(__file__).resolve().parent.parent)
    ns = ap.parse_args(argv)

    try:
        outputs = build_outputs(ns.root)
    except (ValueError, KeyError, FileNotFoundError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    stale = [p for p, text in outputs.items() if not p.exists() or p.read_text() != text]
    rel = [str(p.relative_to(ns.root)) for p in stale]
    if ns.check:
        if stale:
            print("stale generated files (run `npm run generate:index`):", *rel, sep="\n  ")
            return 1
        print("article index up to date")
        return 0
    for p in stale:
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(outputs[p])
    print("updated:" if stale else "no changes", *rel, sep="\n  " if stale else "")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
